# Generated by Django 3.1.2 on 2021-04-24 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0002_auto_20210424_1932'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='vacancy_request',
            field=models.ManyToManyField(blank=True, null=True, to='vacancies.Vacancy'),
        ),
    ]
