# Generated by Django 3.1.2 on 2021-04-24 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=512, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('PY', 'Python'), ('JA', 'Java'), ('SC', 'Scala'), ('NE', 'C#/.NET'), ('NO', 'Node.js'), ('RB', 'Ruby'), ('PHP', 'PHP'), ('FE', 'Frontend/HTML'), ('AN', 'Android'), ('GO', 'Go'), ('C', 'C/C++/Embedded'), ('UI', 'UI/UX Designer'), ('QA', 'QA Automation/Manual'), ('PM', 'Project Manager'), ('BA', 'Business analyst'), ('DS', 'Data science'), ('DO', 'DevOps'), ('HR', 'HR recruiter')], max_length=256)),
            ],
        ),
    ]
